import type { LabeledConfidenceView, TraceabilityView, UncertaintyView } from '../dashboard/dashboard.types';
import type { ReasoningContext, ReasoningDraft, ReasoningResponse } from './reasoning.types';

/**
 * Stage 7: Formatting (implementation architecture §5-§6). Confidence,
 * Evidence, and Uncertainty are never generated by the model -- they are
 * read directly from `ReasoningContext`, which was itself read directly
 * from already-computed, already-tested services. The model's own
 * `ReasoningDraft` supplies only prose fields (`reasoning`,
 * `contradictions`, `suggestedNextSteps`, `uncertaintyNotes`,
 * `behaviorNotes`) and which dimensions it drew on -- never a Confidence
 * value or a Traceability record of its own (Constitution §12.6).
 */
function extractEvidence(context: ReasoningContext): {
  confidence: readonly LabeledConfidenceView[];
  uncertainty: UncertaintyView;
  evidence: readonly TraceabilityView[];
} {
  if (context.kind === 'INSTRUMENT') {
    if (context.asset.readingFailureReason || !context.asset.reading) {
      return {
        confidence: [],
        evidence: [],
        uncertainty: { dataQuality: 'MISSING', assumptions: [], notes: [context.asset.readingFailureReason ?? 'No Confluence reading is available for this instrument.'] },
      };
    }
    const lead = context.asset.reading.topContributors[0];
    if (!lead) {
      return {
        confidence: [],
        evidence: [],
        uncertainty: { dataQuality: 'GAPS_PRESENT', assumptions: [], notes: ['No contributing Provider produced an interpretation for this instrument.'] },
      };
    }
    return {
      confidence: [lead.detectionConfidence, lead.interpretationConfidence, lead.regimeAdjustedConfidence, lead.methodologyConfidenceCeiling],
      evidence: [lead.traceability],
      uncertainty: lead.uncertainty,
    };
  }
  if (context.kind === 'PORTFOLIO') {
    return {
      confidence: [],
      evidence: [],
      uncertainty: {
        dataQuality: 'COMPLETE',
        assumptions: [],
        notes: ['Portfolio analytics has no per-dimension Confidence/Traceability model -- reasoning is based on computed portfolio metrics only.'],
      },
    };
  }
  // TRACKED_ASSETS
  return {
    confidence: [],
    evidence: [],
    uncertainty: {
      dataQuality: context.trackedAssets.instrumentsFailed.length > 0 ? 'GAPS_PRESENT' : 'COMPLETE',
      assumptions: [],
      notes: [
        `Readiness: ${context.trackedAssets.readiness}.`,
        ...(context.trackedAssets.instrumentsFailed.length > 0 ? [`${context.trackedAssets.instrumentsFailed.length} instrument(s) could not be evaluated.`] : []),
        'Per-instrument Confidence detail is available via the Dashboard/Morning Brief; this response synthesizes across the tracked set.',
      ],
    },
  };
}

/** Maps a validated `ReasoningDraft` + the `ReasoningContext` it was validated against into the public `ReasoningResponse`. */
export function formatReasoningResponse(draft: ReasoningDraft, context: ReasoningContext): ReasoningResponse {
  const { confidence, evidence, uncertainty } = extractEvidence(context);
  return {
    reasoning: draft.reasoning,
    confidence,
    uncertainty,
    evidence,
    contradictions: draft.contradictions,
    suggestedNextSteps: draft.suggestedNextSteps,
    behaviorNotes: draft.behaviorNotes,
    scope: { description: context.scopeDescription, modulesUsed: context.modulesUsed },
    generatedAt: context.generatedAt,
    failureReason: null,
  };
}

/** A disclosed pipeline-stage failure -- mirrors WorkspaceService.readingFailureReason (Constitution §4.1: disclose, never fabricate). */
export function formatFailureResponse(reason: string, context?: ReasoningContext): ReasoningResponse {
  return {
    reasoning: '',
    confidence: [],
    uncertainty: { dataQuality: 'MISSING', assumptions: [], notes: [] },
    evidence: [],
    contradictions: [],
    suggestedNextSteps: [],
    behaviorNotes: [],
    scope: { description: context?.scopeDescription ?? 'unavailable', modulesUsed: context?.modulesUsed ?? [] },
    generatedAt: new Date().toISOString(),
    failureReason: reason,
  };
}
