import type { LabeledConfidenceView, TraceabilityView, UncertaintyView } from '../dashboard/dashboard.types';
import type { WorkspaceService } from '../workspace/workspace.service';
import type { PortfoliosService } from '../portfolios/portfolios.service';
import type { AnalyticsService } from '../analytics/analytics.service';
import type { MorningBriefResponse } from '../morning-brief/morning-brief.types';

/** Exactly one scope may be set; an unset scope resolves to the trader's tracked-asset set (ReasoningContextService.buildTrackedAssetsContext). Enforced at the DTO layer by `reasoningAskSchema`. */
export interface ReasoningScope {
  readonly assetId?: string;
  readonly portfolioId?: string;
}

/** WorkspaceService.getWorkspace()'s own return shape, reused as-is -- never redeclared field-by-field. */
export type WorkspaceSnapshot = Awaited<ReturnType<WorkspaceService['getWorkspace']>>;

export interface PortfolioSnapshot {
  readonly portfolio: Awaited<ReturnType<PortfoliosService['findOwned']>>;
  readonly analytics: Awaited<ReturnType<AnalyticsService['getPortfolioAnalytics']>>;
}

/**
 * The bounded, already-computed evidence bag the Reasoning Pipeline's
 * Context Assembly stage produces (implementation architecture §5-§6).
 * A discriminated union, not three optional fields -- the prompt builder
 * and validator both switch on `kind` and get exhaustiveness checking
 * rather than needing to guard against an impossible combination.
 */
export type ReasoningContext =
  | {
      readonly kind: 'INSTRUMENT';
      readonly scopeDescription: string;
      readonly modulesUsed: readonly string[];
      readonly generatedAt: string;
      readonly asset: WorkspaceSnapshot;
    }
  | {
      readonly kind: 'PORTFOLIO';
      readonly scopeDescription: string;
      readonly modulesUsed: readonly string[];
      readonly generatedAt: string;
      readonly portfolio: PortfolioSnapshot;
    }
  | {
      readonly kind: 'TRACKED_ASSETS';
      readonly scopeDescription: string;
      readonly modulesUsed: readonly string[];
      readonly generatedAt: string;
      readonly trackedAssets: MorningBriefResponse;
    };

/**
 * The model's own raw structured output (Gemini `responseJsonSchema`
 * conformance -- `reasoning-prompt-builder.util.ts` `RESPONSE_SCHEMA`).
 * Deliberately carries NO confidence value, evidence object, or
 * traceability record of its own -- those are never generated by the
 * model, only ever read from `ReasoningContext` and attached by
 * `reasoning-formatter.util.ts` (Constitution §12.6: never let a model
 * invent a Confidence number).
 */
export interface ReasoningDraft {
  readonly reasoning: string;
  readonly referencedDimensions: readonly string[];
  readonly contradictions: readonly string[];
  readonly suggestedNextSteps: readonly string[];
  readonly uncertaintyNotes: readonly string[];
  readonly behaviorNotes: readonly string[];
}

/** The complete, structured response for `POST /reasoning/ask` -- no raw model text ever escapes this shape. */
export interface ReasoningResponse {
  readonly reasoning: string;
  readonly confidence: readonly LabeledConfidenceView[];
  readonly uncertainty: UncertaintyView;
  readonly evidence: readonly TraceabilityView[];
  readonly contradictions: readonly string[];
  readonly suggestedNextSteps: readonly string[];
  readonly behaviorNotes: readonly string[];
  readonly scope: { readonly description: string; readonly modulesUsed: readonly string[] };
  readonly generatedAt: string;
  /** Populated, never thrown, on any pipeline-stage failure -- mirrors WorkspaceService.readingFailureReason (Constitution §4.1 honesty rule). All other fields are empty/neutral defaults when this is set. */
  readonly failureReason: string | null;
}
